### ISSUE TITLE
Patch for /trunk/EchoMonitor/src/locale/ru_RU/EchoMonitor.properties

### ISSUE THREAD

**Issue by GoogleCodeExporter** [mpuusaar/echomonitor#1]
```
Täiendasin mõned lüngad venekeelses tõlkefailis. Juri
```

Original issue reported on code.google.com by `jur...@gmail.com` on 13 Sep 2013 at 5:51

Attachments:
- [EchoMonitor.properties.patch](https://storage.googleapis.com/google-code-attachments/echomonitor/issue-1/comment-0/EchoMonitor.properties.patch)

**Comment by mpuusaar** [comment]
Issue was resolved with the 0.9.14 release.
